version: '3'

services:
  certbot:
    image: certbot/certbot:v2.11.0
    container_name: certbot
    restart: 'no'
    networks:
      - default
    ports:
      - 80:80/tcp
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot:/var/lib/letsencrypt
    entrypoint:
      - certbot
      - certonly
      - --standalone
      - --preferred-challenges
      - http
      - --expand
      - -d
      - muflone.com
      - -d
      - www.muflone.com
      - -d
      - archlinux.muflone.com
      - -d
      - nextcloud.muflone.com
      - -d
      - paste.muflone.com
      - -d
      - url.muflone.com
      - -d
      - repositories.muflone.com
      - -d
      - blog.muflone.com
      - -d
      - gnomeshell.muflone.com
      - -d
      - pygtk.muflone.com
      - -d
      - ubuntutrucchi.muflone.com
      - -d
      - uptime.muflone.com
      - -d
      - vbsimple.muflone.com
      - -d
      - vbsimple.net
      - -d
      - www.vbsimple.net
      - --email=webreg@muflone.com
      - --agree-tos
      - --no-eff-email
#      - --dry-run

networks:
  default:
    name: certbot
    driver: bridge
    enable_ipv6: false

